### ISSUE TITLE
Get-Token function is broken

### ISSUE THREAD

**Issue by Letouane** [lmbringas/packtpub-downloader#31]
Thank you for the great work, the script worked like a charm but since few days the website has been upgraded and seems now to use ReCaptcha to secure the access.

Dumping the request JSON response in get-token function in user.py :

```
**{'message': 'The recaptcha solution is missing.', 'errorCode': 7000035, 'errorId': 'b494baa7-255c-4c50-8864-a45ef32d3b0e'}
<Response [400]>**
Error login,  check user and password
Traceback (most recent call last):
  File "main.py", line 226, in <module>
    main(sys.argv[1:])
  File "main.py", line 195, in main
    user = User(email, password)
  File "E:\Utilisateurs\letouane\Downloads\packtpub-downloader-master\user.py", line 27, in __init__
    self.header["Authorization"] = self.get_token()
  File "E:\Utilisateurs\letouane\Downloads\packtpub-downloader-master\user.py", line 44, in get_token
    print("Error {}".format(e))
NameError: name 'e' is not defined
```

I'm trying to adapt the script but I'm not sure I'll succeed.

**Comment by caglartoklu** [comment]
There seems to be 2 problems here:

1 The user can not be authenticated.
2 If the user can not be authenticated, there is no `e` to print since there is no try-except in that scope.

It is this line:
https://github.com/lmbringas/packtpub-downloader/blob/457395e3ae6d7d85e6f08a3161f50f133ec92b73/user.py#L39

**Comment by Letouane** [comment]
As I understand the code, in a previous version of their website, there was an "e" which can fulfill the code of the line 39.
I modified my copy of the code in order to print the response and its HTTP status:
```
        r = requests.post(url, json={'username':self.username, 'password':self.password})
        print(r.json())
        print(r)
        if r.status_code == 200:
            print("You are in!")
            return 'Bearer ' + r.json()['data']['access']

        # except should happend when user and pass are incorrect
        print("Error login,  check user and password")
        print("Error {}".format(e))
        sys.exit(2)
```
That way I can output the problem that lead to the error :
```
{'message': 'The recaptcha solution is missing.', 'errorCode': 7000035, 'errorId': 'b494baa7-255c-4c50-8864-a45ef32d3b0e'}
<Response [400]>
```

The problem doesn't appear anymore, I think I only had to wait few days. Thank you for your time and interest in my issue.
